--Create a materialized view that lists the total revenue generated by each film

CREATE MATERIALIZED VIEW film_revenue_mv AS
SELECT f.title, SUM(p.amount) AS total_revenue
FROM film f
LEFT JOIN inventory i ON f.film_id = i.film_id
LEFT JOIN rental r ON i.inventory_id = r.inventory_id
LEFT JOIN payment p ON r.rental_id = p.rental_id
GROUP BY f.title;


--Retrieve data from the materialized view

SELECT * FROM film_revenue_mv;